name: Copy Pages
on:
  push:
    branches:
      # Replace with whatever your source branch is!
      - main
jobs:
  copy:
    name: Copy Pages
    runs-on: ubuntu-latest
    steps:
      # Check out the code that was just commited to './source'
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          path: source

      # Check out the 'gh-pages' branch
      - name: Checkout gh-pages
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: target

      # Optional: Run any static-site building you need here!

      # Delete the old content

      # Copy the content (feel free to adjust the source directory!)
      - name: Copy docs
        run: rsync -av --exclude='.git' --delete ./source/ ./target/

      - name: Commit to target
        working-directory: ./target
        run: |
          set -exo pipefail
          git add -A
          if git diff HEAD --exit-code; then
            # Commit will fail if there's nothing to commit!
            echo "No changes to commit!"
          else
            git commit -m"Synchronized docs from $GITHUB_SHA on $GITHUB_REF" --author="github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} gh-pages
          fi